DevClubLMS/urls.py
from django.contrib import admin
from django.urls import path
import app_users
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from grading import views as grade_view




urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('app_users.urls')),
    path("lms/",include('app_curriculum.urls')),
    path('grades/', grade_view.index)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_curriculum/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'app_curriculum'

urlpatterns = [
    path('',views.StandardListView.as_view(),name = 'standard_list'),
    path('<slug:slug>/',views.SubjectListView.as_view(),name = 'subject_list'),
    path('<str:standard>/<slug:slug>/',views.LessonListView.as_view(),name = 'lesson_list'),
    path('<str:standard>/<str:slug>/create/',views.LessonCreateView.as_view(),name = 'lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/',views.LessonDetailView.as_view(),name = 'lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/',views.LessonUpdateView.as_view(),name ='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/',views.LessonDeleteView.as_view(),name ='lesson_delete'),
]
urlpatterns += staticfiles_urlpatterns()

app_users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='user_logout'),
]

demo/LearningDjango/LearningDjango/urls.py
from django.contrib import admin
from django.urls import path
from playing import views as play_view
from grading import views as grade_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('playing/', play_view.index),
    path('playing/bye', play_view.bye),
    path('playing/hi/<slug:name>', play_view.hi),
    path('grades/', grade_view.index)
]

app_curriculum/models.py
from ast import arg
import os

from distutils.command.upload import upload
from re import M
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse
# Create your models here.

class Standard(models.Model):
    name = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(null=True,blank=True)
    description = models.TextField(max_length=400,blank=True)

    def __str__(self):
        return self.name
    
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

# course class code;
def save_course_image(instance,filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    if instance.course_id:
        filename = f"SubjectPictures/{instance.course_id}.{ext}"
    return os.path.join(upload_to,filename)



class Course(models.Model):
    course_id = models.CharField(max_length=15,unique=True)
    name = models.CharField(max_length=30)
    slug = models.SlugField(null=True,blank=True)
    standard = models.ForeignKey(Standard,on_delete=models.CASCADE,related_name='subjects')
    image = models.ImageField(upload_to= save_course_image,blank=True,verbose_name='Course Image')
    description = models.TextField(max_length=250,blank=True)

    def __str__(self):
        return self.name

    def save(self,*args, **kwargs):
        self.slug = slugify(self.course_id)
        super().save(*args,**kwargs)


### Lesson Model code;_
def save_lesson_files(instance,filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]

    if instance.lesson_id:
        filename=f'lesson_media/{instance.lesson_id}/{instance.lesson_id}.{ext}'
        if os.path.exists(filename):
            new_name = str(instance.lesson_id) + str(1)
            filename = f'lesson_media/{instance.lesson_id}/{new_name}.{ext}'
    return os.path.join(upload_to,filename)


class Lesson(models.Model):
    lesson_id = models.CharField(max_length=18,unique=True)
    Standard = models.ForeignKey(Standard,on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    Course = models.ForeignKey(Course,on_delete=models.CASCADE,related_name='lessons')
    name = models.CharField(max_length=50)
    position = models.PositiveSmallIntegerField(verbose_name='Chapter No:')
    slug = models.SlugField(null=True,blank=True)
    video = models.FileField(upload_to=save_lesson_files,verbose_name='Video',blank=True,null=True)
    ppt = models.FileField(upload_to=save_lesson_files,verbose_name='Presentations',blank=True)
    Notes = models.FileField(upload_to=save_lesson_files,verbose_name="Notes",blank=True)

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.name
    
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)
    
    def get_absolute_url(self):
        return reverse("app_curriculum:lesson_list", kwargs={"slug": self.Course.slug,'standard':self.Standard.slug})
    

class Comment(models.Model):
    lesson_name = models.ForeignKey(Lesson,null=True,on_delete=models.CASCADE,related_name='comments')
    comment_name  = models.CharField(max_length=100,blank=True)

    author = models.ForeignKey(User,on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.comment_name = slugify('comment by' + '-'+str(self.author) + str(self.date_added))
        super().save(*args,**kwargs)

    def __str__(self):
        return self.comment_name

    class Meta:
        ordering = ['date_added']

class Reply(models.Model):
    comm_name = models.ForeignKey(Comment,on_delete=models.CASCADE,related_name='replies')
    reply_body = models.TextField(max_length=400)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "reply to " + str(self.comm_name.comment_name)

app_curriculum/forms.py
from xml.etree.ElementTree import Comment
from django import forms
from .models import Lesson,Comment,Reply

class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ('lesson_id','name','position','video','ppt','Notes')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        labels = {'body':'comment'}
        widgets  = {
            'body':forms.Textarea(attrs={'class':'form-control','rows':4,'cols':70,'placeholder':"Enter Your comment"})
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)
        widgets = {
            'reply_body':forms.Textarea(attrs={'class':'form-control','rows':2,'cols':10})
        }

app_curriculum/views.py
from http.client import HTTPResponse
from urllib import request
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView,DetailView,ListView,FormView,CreateView,UpdateView,DeleteView

from .forms import CommentForm, LessonForm, ReplyForm
from app_curriculum.models import Standard
from .models import Standard, Course, Lesson
from django.contrib.auth.mixins import AccessMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.



class StandardListView(LoginRequiredMixin,ListView):
    login_url = reverse_lazy('user_login',current_app='app_users')
    redirect_field_name = 'redirect_to'
    template_name = 'app_curriculum/standard_list_view.html'
    context_object_name = 'standards'
    model = Standard


class SubjectListView(DetailView):
    context_object_name = 'standards'
    model = Standard
    template_name = 'app_curriculum/subject_list_view.html'

class LessonListView(DetailView):
    context_object_name = 'subjects'
    model = Course
    template_name = 'app_curriculum/lesson_list_view.html'

class LessonDetailView(DetailView,FormView):
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'app_curriculum/lesson_detail_list_view.html'
    form_class = CommentForm
    second_form_class = ReplyForm

    #handle each reply and comment form as per need
    def get_context_data(self, **kwargs):
        context = super(LessonDetailView,self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()

        return context
    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.Standard
        subject = self.object.Course
        return reverse_lazy('app_curriculum:lesson_detail',kwargs={'standard':standard.slug,'subject':subject.slug,'slug':self.object.slug})

    def form_valid(self,form):
        self.object = self.get_object()
        fm = form.save(commit = False)
        fm.author = self.request.user
        fm.lesson_name = self.object.comments.name
        fm.lesson_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self,form):
        self.object = self.get_object()
        fm = form.save(commit = False)
        fm.author = self.request.user
        fm.comm_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())




    def post(self,request,*args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.form_class
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)

        if form_name == 'form' and form.is_valid():
            print('comment form is returned'
            )
            return self.form_valid(form)
        elif form_name == 'form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)
    
class LessonCreateView(UserPassesTestMixin,CreateView):
    form_class = LessonForm
    context_object_name = 'subject'
    model = Course
    template_name = 'app_curriculum/lesson_create.html'
    permission_denied_message = 'Only staff can create lessons'
  
    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.standard
        return reverse_lazy('app_curriculum:lesson_list',kwargs={'standard':standard.slug,'slug':self.object.slug})

    def form_valid(self,form,*args,**kwargs):
        self.object = self.get_object()
        my_form = form.save(commit=False)
        my_form.created_by = self.request.user
        my_form.Standard = self.object.standard
        my_form.Course = self.object
        my_form.save()
        return HttpResponseRedirect(self.get_success_url())
    
    def test_func(self):
        return self.request.user.is_staff



class LessonUpdateView(UserPassesTestMixin,UpdateView):
    fields = ('name','position','video','ppt','Notes')
    model = Lesson
    template_name = 'app_curriculum/lesson_update.html'
    context_object_name = 'lessons'
    def test_func(self):
        return self.request.user.is_staff


class LessonDeleteView(UserPassesTestMixin,DeleteView):
    model = Lesson
    context_object_name = 'lessons'
    template_name = 'app_curriculum/lesson_delete.html'
    def test_func(self):
        return self.request.user.is_staff
    def get_success_url(self):
        standard = self.object.Standard
        Course = self.object.Course
        return reverse_lazy('app_curriculum:lesson_list',kwargs={'standard':standard.slug,'slug':Course.slug})

app_curriculum/templates/app_curriculum/lesson_create.html
{% extends 'base.html' %} {% load crispy_forms_tags%} {% block content %}
<div class="container col-6">
  <form method="POST">
    {% load crispy_forms_tags%} {%csrf_token%} {{form|crispy}}

    <input class="btn btn-primary" type="submit" value="Submit" />
  </form>
</div>
{% endblock content %}

app_curriculum/templates/app_curriculum/lesson_delete.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags%}

<h3>Are you sure you want to delete ?</h3>
<form method="post">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="Confirm Delete" />
  <a
    class="btn btn-success"
    href="{% url 'app_curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.Course.slug slug=lessons.slug %}"
  >
    Cancel Delete
  </a>

  {% endblock content %}
</form>

app_curriculum/templates/app_curriculum/lesson_detail_list_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}

{% block content %}
</br>
<h3> Lesson Materials </h3>
<p> Created on {{lessons.created_at}} by {{lessons.created_by}} </p> <br>
{% if lessons.video %}
<div class="container embed-responsive embed-responsive-21by9"> 
    <video name='demo' controls autoplay width='50%' height='40%'>
    <source src="{{lessons.video.url}}" type="video/mp4"></source>
  </video> </div></br>{% endif %}
<a class="btn btn-primary btn-lg" href= "{% url 'app_curriculum:lesson_update' standard=lessons.Standard.slug subject=lessons.Course.slug slug=lessons.slug %}"> Update Lesson Details </a>
<a class="btn btn-danger btn-lg" href= "{% url 'app_curriculum:lesson_delete' standard=lessons.Standard.slug subject=lessons.Course.slug slug=lessons.slug %}"> Delete Chapter  </a>
</br>
<br>


<h3> Post your comment or question below: </h4>
    <form method = 'post'>
        <div class = 'form-group'>
            {% csrf_token %}
            {{form|crispy}}
            <input type = 'submit' name='form' value='Add Comment' class='btn btn-info btn-sm'>
        </div>
    </form>

    {% for comment in lessons.comments.all  %}

    
    <h4> {{comment.author}} <small> <i> Posted on {{comment.date_added}} </i></small> </h4>
    <p> {{comment.body}} </p>
    {% for reply in comment.replies.all  %}

    <h5> {{reply.author}} <small><i> Replied on {{reply.date_added}} </i></small> </h5>
    <p> {{reply.reply_body}}</p>
    {% endfor %}
    
    <form method = 'post'>
        <input type = 'hidden' name = 'comment.id' value="{{comment.id}}">
        <input type = 'hidden' name = 'commend.comment_name' value="{{comment.comment_name}}">
        {% csrf_token %}
        {{form2|crispy}}
        <input type = 'submit' name = 'form2' value='Add Reply' class='btn btn-warning btn-sm'>
    </form>
    {% endfor %}
 



{% endblock content %}

app_curriculum/templates/app_curriculum/lesson_list_view.html
{% extends 'base.html' %} {% block content %}
<br>

<div class="card" style="width: 18rem; margin:5px;padding:2px">
  {% for lesson in subjects.lessons.all %}
  <ul class="list-group list-group-flush">
    <li class="list-group-item"> <a href="{% url 'app_curriculum:lesson_detail' slug=lesson.slug subject=subjects.slug standard=lesson.Standard.slug %}">
      <bold>Chapter-{{lesson.position}}: {{lesson.name}} </bold> </a></li>  
    
    </ul>
    {% endfor %}
    
</div>

 <a class='btn btn-success' <a href="{% url 'app_curriculum:lesson_create' standard=subjects.standard.slug slug=subjects.slug %}">  
  Create Lesson</a>
</div>
{% endblock content%}

app_curriculum/templates/app_curriculum/lesson_update.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags%}
<div class="container col-6">
  <form method="post">
    {% csrf_token %} {{form|crispy}}
    <input class="btn btn-primary" type="submit" name="" value="Update" />
    <a
      class="btn btn-warning"
      href="{% url 'app_curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.Course.slug slug=lessons.slug %}"
    >
      Cancel Update
    </a>
  </form>
</div>

{% endblock content %}

app_curriculum/templates/app_curriculum/standard_list_view.html
{% extends 'base.html' %} {% block content %} {% for standard in standards %}

  
    <div class="card col-6 container">
      <h5 class="card-header">{{standard.name}}</h5>
      <div class="card-body">
        <h5 class="card-title">{{standard.name}}</h5>
        <p class="card-text">{{standard.description}}</p>
        <a
          href="{% url 'app_curriculum:subject_list' slug=standard.slug %}"
          class="btn btn-primary"
          >Courses</a
        >
      </div>
    </div>
  </div>
</div>

<br />

{% endfor %} {% endblock content %}

app_curriculum/templates/app_curriculum/subject_list_view.html
{% extends 'base.html' %} {%load static%} {% block content %}
<br />
<div class="container">
  <div class="row">
    {% for subject in standards.subjects.all %}
    <div class="col-sm-6">
      <div class="card" style="width: 18rem; margin: 5px">
        <img
          src="/media/{{subject.image}}"
          class="card-img-top"
          alt="subject thumbnail"
        />
        <div class="card-body">
          <h5 class="card-title">{{subject.course_id}}</h5>
          <p class="card-text">{{subject.description|truncatechars:80}}</p>
          <a
            href="{% url 'app_curriculum:lesson_list' slug=subject.slug standard=standards.slug %}"
            class="btn btn-info"
            >{{subject.name}}</a
          >
        </div>
      </div>
    </div>

    {% endfor %}
  </div>
</div>
{% endblock %}