DevClubLMS/urls.py
from django.contrib import admin
from django.urls import path
import app_users
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from grading import views as grade_view




urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('app_users.urls')),
    path("lms/",include('app_curriculum.urls')),
    path('grades/', grade_view.index)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_curriculum/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'app_curriculum'

urlpatterns = [
    path('',views.StandardListView.as_view(),name = 'standard_list'),
    path('<slug:slug>/',views.SubjectListView.as_view(),name = 'subject_list'),
    path('<str:standard>/<slug:slug>/',views.LessonListView.as_view(),name = 'lesson_list'),
    path('<str:standard>/<str:slug>/create/',views.LessonCreateView.as_view(),name = 'lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/',views.LessonDetailView.as_view(),name = 'lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/',views.LessonUpdateView.as_view(),name ='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/',views.LessonDeleteView.as_view(),name ='lesson_delete'),
]
urlpatterns += staticfiles_urlpatterns()

app_users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='user_logout'),
]

demo/LearningDjango/LearningDjango/urls.py
from django.contrib import admin
from django.urls import path
from playing import views as play_view
from grading import views as grade_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('playing/', play_view.index),
    path('playing/bye', play_view.bye),
    path('playing/hi/<slug:name>', play_view.hi),
    path('grades/', grade_view.index)
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <title>LMS</title>
  </head>
  
  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand btn-secondary btn" href="{% url 'app_curriculum:standard_list'  %}"
      >Learning Management System</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" href="{% url 'index'  %}"> Home <span class="sr-only">(current)</span></a
          >
          <a class="nav-link active" href="{% url 'register' %}">Register</a>
          {% if user.is_authenticated %}
          <a class="nav-link active" href="{% url 'user_logout'  %}">Logout</a>
          {%else%}
          <a class="nav-link active" href="{% url 'user_login'  %}">Login</a>
          {%endif%}
        </div>
      </div>
    </nav>
  </div>
  </div>
    
    {%load static%}
   
  {% block content %}
  
  
  {% endblock content %}
  <br>
  <footer  class="bg-light fixed-bottom text-center text-sm-start">
    <!-- Copyright -->
    <div class="text-center p-2" style="background-color: rgba(0, 0, 0, 0);">
     Website Developed By
      <a class="text-dark" target='_blank' href="https://linkedin.com/in/emraanadil">Adil Imran Pintoo</a>
    </div>
    <!-- Copyright -->
  </footer>

    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous">
  


</script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active" data-interval="1000">
          <img src="{% static 'images/lms3.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item" data-interval="1000">
        <img src="{% static 'images/lms1.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item" data-interval="1000">
        <img src="{% static 'images/lms4.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item" data-interval="1000">
        <img src="{% static 'images/lms2.jpg' %}" class="d-block w-100" alt="...">
      </div>
    </div>
  </div>
</div>
 


{% endblock content %}